import { CFG, Colors, Relics } from './config.js';
import { clamp, rand, pick, speedOf, sign, circleRect } from './utils.js';

export class Game {
  constructor(canvas, button) {
    this.canvas = canvas; this.button = button; this.W = 960; this.H = 600; this.dpr = 1;
    this.keys = new Set(); this.pointer = { active:false, x:70, y:300, lastX:null, lastY:null };
    this.mode = 'title'; this.level = 0; this.score = 0; this.best = Number(localStorage.getItem('thats-a-paddlin-best') || 0);
    this.combo = 0; this.comboTimer = 0; this.spinIntent = 0; this.freeServe = false;
    this.player = null; this.enemy = null; this.balls = []; this.blocks = []; this.previews = [];
    this.particles = []; this.floaters = []; this.notes = []; this.draft = []; this.relics = [];
    this.mods = this.baseMods(); this.flash = 0; this.shake = 0; this.err = '';
  }
  baseMods(){return{maxHp:5,paddleScale:1,paddleSpeed:1,ballSpeed:1,damage:1,shield:0,crit:0,spinPower:1,extraBalls:0,scoreScale:1,phaseSafe:false,pinholeChance:.18,entanglePower:1,collapseBonus:80,portalMastery:false,gravityWell:0,bossBane:0,trailPower:1,stunBonus:0}}
  levelT(){return clamp(this.level/CFG.maxLevel,0,1)} isBossLevel(l=this.level){return l>0&&l%5===0}
  playerZone(){return{x1:28,x2:this.W/3,y1:24,y2:this.H-24}} enemyZone(){return{x1:this.W*2/3,x2:this.W-28,y1:24,y2:this.H-24}}
  notify(text,color=Colors.text,life=1.3){this.notes.push({text,color,life,maxLife:life}); if(this.notes.length>7)this.notes.shift()}
  resize(){this.dpr=Math.min(devicePixelRatio||1,2);this.W=Math.max(360,innerWidth||960);this.H=Math.max(420,innerHeight||600);this.canvas.width=Math.floor(this.W*this.dpr);this.canvas.height=Math.floor(this.H*this.dpr);this.canvas.style.width=this.W+'px';this.canvas.style.height=this.H+'px';this.clampActors()}
  clampActors(){if(this.player){let z=this.playerZone(),p=this.player;p.x=clamp(p.x,z.x1+p.w/2,z.x2-p.w/2);p.y=clamp(p.y,z.y1+p.h/2,z.y2-p.h/2)}if(this.enemy){let z=this.enemyZone(),e=this.enemy;e.x=clamp(e.x,z.x1+e.w/2,z.x2-e.w/2);e.y=clamp(e.y,z.y1+e.h/2,z.y2-e.h/2)}}
  makePaddle(x,y,color,hp,h,speed,kind){return{x,y,oldX:x,oldY:y,vx:0,vy:0,w:CFG.paddle.w,h,baseH:h,hp,maxHp:hp,color,stamina:1,wait:0,stun:0,inv:0,angle:0,manualAngle:0,angleLocked:false,speed,kind,phase:rand(0,6.28)}}
  enemyKind(){if(this.isBossLevel())return pick(['boss-fractal','boss-worm','boss-entangler','boss-observer']); if(this.level>32)return pick(['seeker','mirror','phase','sniper','guardian']); if(this.level>15)return pick(['seeker','mirror','phase','guardian']); return pick(['rookie','seeker','guardian'])}
  makeEnemy(){let k=this.enemyKind(),b=k.startsWith('boss'),t=this.levelT(),hp=b?Math.floor(8+this.level*1.25):Math.floor(3+this.level*.58+t*10),h=(b?86:CFG.paddle.enemyH)+this.level*(b?.9:.25),speed=b?560+t*980:430+t*990,e=this.makePaddle(this.W-54,this.H/2,b?Colors.red:pick([Colors.purple,Colors.pink,Colors.green,Colors.gold,Colors.blue]),hp,h,speed,k);this.notify(b?'BOSS '+this.level:'ENEMY '+k.toUpperCase(),b?Colors.red:Colors.pink,1.6);return e}
  newRun(){Object.assign(this,{mode:'playing',level:0,score:0,combo:0,comboTimer:0,spinIntent:0,freeServe:true,balls:[],blocks:[],previews:[],particles:[],floaters:[],notes:[],draft:[],relics:[],mods:this.baseMods(),flash:0,shake:0,err:''});this.player=this.makePaddle(70,this.H/2,Colors.cyan,5,CFG.paddle.h,1,'player');this.pointer.active=false;this.pointer.x=this.player.x;this.pointer.y=this.player.y;this.enemy=this.makeEnemy();this.fillBlocks();this.prepareFreeServe();this.syncButton()}
  prepareFreeServe(){this.freeServe=true;this.balls=[];this.notify('LEVEL '+this.level+' - FREE SERVE',Colors.cyan,1.8)}
  launchFreeServe(){if(this.mode!=='playing'||!this.freeServe)return false;this.freeServe=false;this.serve(1+this.mods.extraBalls,1,true);this.notify('SERVE',Colors.cyan,.8);return true}
  serve(n=1,dir=0,from=false){for(let i=0;i<n;i++){let d=dir||pick([-1,1]),v=(CFG.ball.startSpeed+this.level*8)*this.mods.ballSpeed,a=rand(-.42,.42),x=from?this.player.x+35+i*10:this.W/2+rand(-18,18),y=from?this.player.y+rand(-18,18):this.H/2+rand(-70,70);this.makeBall(x,y,Math.cos(a)*v*d,Math.sin(a)*v,clamp(rand(-.55,.55)+this.spinIntent*.45,-1.1,1.1),'none')}}
  maxBalls(){return 4+Math.floor(this.levelT()*5)}
  makeBall(x,y,vx,vy,spin=0,lastHit='none',entangled=null){if(this.balls.length>=this.maxBalls())return null;let b={id:Math.random().toString(36).slice(2),x,y:clamp(y,CFG.pad+CFG.ball.r,this.H-CFG.pad-CFG.ball.r),prevX:x,prevY:y,vx,vy,r:CFG.ball.r,damage:this.mods.damage,spin,lift:0,contact:0,paddleV:0,lastHit,wallBounces:0,wallAt:0,stall:0,warned:false,anchorX:x,anchorY:y,trail:[],entangled};this.balls.push(b);return b}
  blockHp(t){if(t==='shielded')return 4;if(['stone','regen','gravity'].includes(t))return 3;if(t==='bosscore')return 9;if(['portal','wormhole','entangler','observer'].includes(t))return 2;return 1}
  blockColor(t){return{stone:Colors.stone,spike:Colors.pink,portal:Colors.purple,wormhole:Colors.blue,pinhole:Colors.cyan,entangler:Colors.green,mirror:Colors.text,moving:Colors.green,gravity:Colors.purple,regen:Colors.orange,shielded:Colors.cyan,bomb:Colors.red,observer:Colors.gold,bonus:Colors.gold,bosscore:Colors.red}[t]||Colors.brick}
  blockWeights(){let l=this.level;return[['brick',1],['bonus',l>1?.12:0],['stone',l>3?.2:0],['spike',l>6?.14:0],['pinhole',l>4?.13:0],['portal',l>7?.12:0],['entangler',l>9?.1:0],['mirror',l>11?.09:0],['moving',l>13?.13:0],['splitter',l>15?.1:0],['wormhole',l>17?.1:0],['gravity',l>21?.09:0],['regen',l>24?.08:0],['shielded',l>27?.08:0],['bomb',l>34?.07:0],['observer',l>39?.06:0]]}
  randomBlockType(){let a=this.blockWeights(),r=Math.random()*a.reduce((s,x)=>s+x[1],0);for(let x of a){r-=x[1];if(r<=0)return x[0]}return'brick'}
  overlaps(a,b,p=0){return a.x<b.x+b.w+p&&a.x+a.w+p>b.x&&a.y<b.y+b.h+p&&a.y+a.h+p>b.y}
  spawnRect(type='brick'){let scale=type==='bosscore'?2.1:1,w=CFG.blocks.w*scale,h=CFG.blocks.h*scale,minX=122,maxX=this.W-122-w,minY=78,maxY=this.H-78-h,all=this.blocks.concat(this.previews);for(let i=0;i<120;i++){let r={x:rand(minX,maxX),y:rand(minY,maxY),w,h};if(!all.some(o=>this.overlaps(r,o,14)))return r}return{x:rand(minX,maxX),y:rand(minY,maxY),w,h}}
  makeBlock(x,y,type){let hp=this.blockHp(type),scale=type==='bosscore'?2.1:1;return{x,y,baseX:x,baseY:y,w:CFG.blocks.w*scale,h:CFG.blocks.h*scale,type,hp,maxHp:hp,phase:rand(0,6.28),cool:0,regen:0,link:null}}
  targetBlocks(){return this.isBossLevel()?18+Math.floor(this.levelT()*18):clamp(CFG.blocks.base+Math.floor(this.level*.82),CFG.blocks.base,CFG.blocks.max)}
  fillBlocks(){this.blocks=[];this.previews=[];if(this.isBossLevel()){let r=this.spawnRect('bosscore');this.blocks.push(this.makeBlock(r.x,r.y,'bosscore'))}while(this.blocks.length<this.targetBlocks()){let type=this.randomBlockType(),r=this.spawnRect(type);this.blocks.push(this.makeBlock(r.x,r.y,type))}this.linkPortals()}
  linkPortals(){let p=this.blocks.filter(b=>b.type==='portal'||b.type==='wormhole');p.forEach((h,i)=>h.link=p[(i+1)%p.length]||null)}
  scheduleBlock(){let type=this.randomBlockType(),r=this.spawnRect(type),time=clamp(CFG.blocks.respawnBase-this.level*.038,CFG.blocks.respawnMin,CFG.blocks.respawnBase);this.previews.push({...r,type,time,total:time})}
  update(dt){if(this.mode!=='playing'||this.paused){this.updateEffects(dt);return}this.comboTimer=Math.max(0,this.comboTimer-dt);if(!this.comboTimer)this.combo=0;this.flash=Math.max(0,this.flash-dt*1.8);this.shake=Math.max(0,this.shake-dt*22);this.player.inv=Math.max(0,this.player.inv-dt);this.enemy.stun=Math.max(0,this.enemy.stun-dt);this.updatePreviews(dt);this.updateBlocks(dt);this.updatePlayer(dt);this.updateEnemy(dt);this.updateBalls(dt);this.updateQuantum(dt);this.updateEffects(dt);if(!this.balls.length&&!this.freeServe)this.serve(1)}
  updatePreviews(dt){while(this.blocks.length+this.previews.length<this.targetBlocks())this.scheduleBlock();for(let i=this.previews.length-1;i>=0;i--){let p=this.previews[i];p.time-=dt;if(p.time<=0){let b=this.makeBlock(p.x,p.y,p.type);this.blocks.push(b);if(['portal','wormhole'].includes(b.type))this.linkPortals();this.burst(p.x+p.w/2,p.y+p.h/2,this.blockColor(p.type),14);this.notify('BLOCK: '+p.type.toUpperCase(),this.blockColor(p.type),.7);this.previews.splice(i,1)}}}
  updateBlocks(dt){let now=performance.now()/1000;for(let b of this.blocks){b.cool=Math.max(0,b.cool-dt);if(this.level>=14||b.type==='moving'||b.type==='bosscore'){let sc=b.type==='moving'?1:this.level>=30?.55:.25;b.x=b.baseX+Math.sin(now*(1.2+this.levelT()*2.6)+b.phase)*(12+this.level*.8)*sc;b.y=b.baseY+Math.cos(now*(.9+this.levelT()*1.5)+b.phase)*(7+this.level*.5)*sc}if(b.type==='regen'&&b.hp<b.maxHp){b.regen+=dt;if(b.regen>Math.max(.7,2.5-this.levelT()*1.4)){b.hp++;b.regen=0;this.floatText(b.x+b.w/2,b.y,'REGEN',Colors.orange)}}if((b.type==='portal'||b.type==='wormhole')&&Math.random()<dt*.12*this.levelT())this.teleportBlock(b)}}
  teleportBlock(b){let r=this.spawnRect(b.type);b.baseX=b.x=r.x;b.baseY=b.y=r.y;this.burst(b.x+b.w/2,b.y+b.h/2,this.blockColor(b.type),12);this.notify('WORMHOLE SHIFT',Colors.purple,.8)}
  stamina(p,moving,dt,drain){p.wait=Math.max(0,p.wait-dt);if(p.wait>0){p.stamina=clamp(p.stamina+CFG.paddle.staminaRefill*dt,0,1);return 0}if(moving&&p.stamina>0){p.stamina=Math.max(0,p.stamina-drain*dt);if(!p.stamina)p.wait=CFG.paddle.staminaPause;return 1}p.stamina=clamp(p.stamina+CFG.paddle.staminaRefill*dt,0,1);return moving?0:1}
  updatePlayer(dt){let p=this.player,z=this.playerZone();p.h=p.baseH*this.mods.paddleScale;p.oldX=p.x;p.oldY=p.y;this.stamina(p,this.pointer.active&&Math.hypot(this.pointer.x-p.x,this.pointer.y-p.y)>1.5,dt,CFG.paddle.staminaDrain);if(this.pointer.active){p.x=this.pointer.x;p.y=this.pointer.y}p.x=clamp(p.x,z.x1+p.w/2,z.x2-p.w/2);p.y=clamp(p.y,z.y1+p.h/2,z.y2-p.h/2);p.vx=(p.x-p.oldX)/Math.max(dt,.001);p.vy=(p.y-p.oldY)/Math.max(dt,.001);this.updatePlayerAngle(p,dt)}
  updatePlayerAngle(p,dt){let dir=(this.keys.has('KeyD')||this.keys.has('ArrowRight')||this.keys.has('KeyE')?1:0)-(this.keys.has('KeyA')||this.keys.has('ArrowLeft')||this.keys.has('KeyQ')?1:0);this.updateSpinIntent(dir,dt);if(dir){p.angleLocked=true;p.manualAngle=clamp(p.manualAngle+dir*1.65*(this.keys.has('ShiftLeft')||this.keys.has('ShiftRight')?1.8:1)*dt,-CFG.paddle.maxAngle,CFG.paddle.maxAngle)}let target=p.angleLocked?p.manualAngle:Math.atan2(p.vy*.95-p.vx*.36,420)*1.7;target=clamp(target,-CFG.paddle.maxAngle,CFG.paddle.maxAngle);p.angle+=(target-p.angle)*clamp(dt*12,0,1)}
  updateSpinIntent(dir,dt){if(dir){let old=Math.abs(this.spinIntent);this.spinIntent=clamp(this.spinIntent+dir*2.9*dt,-1,1);if(old<.72&&Math.abs(this.spinIntent)>=.72)this.notify('SPIN CHARGED',this.spinIntent>0?Colors.gold:Colors.purple,.7);return}let d=4.2*dt;this.spinIntent=Math.abs(this.spinIntent)<=d?0:this.spinIntent-Math.sign(this.spinIntent)*d}
  updateEnemy(dt){let e=this.enemy,z=this.enemyZone();e.oldX=e.x;e.oldY=e.y;if(e.stun>0){this.stamina(e,false,dt,CFG.paddle.enemyDrain);return}let target=this.balls.filter(b=>b.vx>0).sort((a,b)=>b.x-a.x)[0]||this.balls[0],tx=z.x2-e.w/2,ty=this.H/2;if(target){let travel=target.vx>0?Math.max(0,(e.x-target.x)/Math.max(target.vx,1)):.16,pred=this.predictY(target,travel*(.18+this.levelT()*.8)),mist=rand(-1,1)*(46*(1-this.levelT())**1.6),lead=clamp((target.x-this.W*.5)/(this.W*.5),0,1);ty=pred+mist+Math.sin(performance.now()/(560-this.levelT()*260)+e.phase)*(34*(1-this.levelT()));tx=z.x2-e.w/2-lead*(z.x2-z.x1)*(e.kind==='guardian'?.38:.58);if(e.kind==='mirror')ty=this.H-pred+mist*.4;if(e.kind==='sniper')tx=z.x1+e.w/2+(z.x2-z.x1)*.18}let scale=this.stamina(e,Math.hypot(tx-e.x,ty-e.y)>1.5,dt,CFG.paddle.enemyDrain),step=e.speed*(.62+this.levelT()*.92)*scale*dt;e.x+=clamp(tx-e.x,-step,step);e.y+=clamp(ty-e.y,-step,step);e.x=clamp(e.x,z.x1+e.w/2,z.x2-e.w/2);e.y=clamp(e.y,z.y1+e.h/2,z.y2-e.h/2);e.vx=(e.x-e.oldX)/Math.max(dt,.001);e.vy=(e.y-e.oldY)/Math.max(dt,.001)}
  predictY(b,sec){let y=b.y+b.vy*sec,top=CFG.pad+b.r,bot=this.H-CFG.pad-b.r,span=bot-top;if(span<=0)return b.y;y=(y-top)%(span*2);if(y<0)y+=span*2;if(y>span)y=span*2-y;return top+y}
  updateBalls(dt){for(let i=this.balls.length-1;i>=0;i--){let b=this.balls[i];this.pushTrail(b,dt);this.applyGravity(b,dt);this.applySpin(b,dt);this.stabilize(b);b.prevX=b.x;b.prevY=b.y;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.y<CFG.pad+b.r)this.wallBounce(b,true);if(b.y>this.H-CFG.pad-b.r)this.wallBounce(b,false);this.paddleHit(b,this.player,true);this.paddleHit(b,this.enemy,false);this.blockHit(b);this.stabilize(b);this.updateStall(b,dt);if(b.x<-48){this.balls.splice(i,1);this.hurtPlayer(1)}else if(b.x>this.W+48){this.balls.splice(i,1);this.hitEnemy(this.goalDamage(b),this.W-74,b.y)}}}
  trailRatio(b){return clamp(speedOf(b)/CFG.ball.speedSoftCap,0,2.4)}
  trailLimit(b){return Math.round(clamp(CFG.ball.trailMin+this.trailRatio(b)*(CFG.ball.trailMax-CFG.ball.trailMin),CFG.ball.trailMin,CFG.ball.trailMax))}
  pushTrail(b,dt){let r=this.trailRatio(b),life=(.22+Math.min(2,r)*(CFG.ball.trailLifeMax-.22))*this.mods.trailPower,rad=b.r*(.75+Math.min(2.2,r)*CFG.ball.trailWidthBoost);b.trail.push({x:b.x,y:b.y,life,max:life,r:rad,speed:speedOf(b),full:r>=1});while(b.trail.length>this.trailLimit(b))b.trail.shift();b.trail.forEach(t=>t.life-=dt);b.trail=b.trail.filter(t=>t.life>0);if(r>=1&&Math.random()<dt*14){let a=rand(0,Math.PI*2);this.particles.push({x:b.x,y:b.y,vx:Math.cos(a)*rand(30,160),vy:Math.sin(a)*rand(30,160),r:rand(1,3),color:Math.random()<.5?Colors.cyan:Colors.gold,life:rand(.22,.55)})}}
  applyGravity(b,dt){let wells=this.blocks.filter(x=>x.type==='gravity'),power=this.mods.gravityWell+wells.length*.18;if(power<=0)return;for(let g of wells){let cx=g.x+g.w/2,cy=g.y+g.h/2,dx=cx-b.x,dy=cy-b.y,d2=dx*dx+dy*dy;if(d2>1&&d2<90000){let f=power*11000/d2;b.vx+=dx*f*dt;b.vy+=dy*f*dt}}}
  soft(v,c,k){return!Number.isFinite(v)?c:v<=c?v:c+(v-c)*k} softSigned(v,c,k){return Math.sign(v||1)*this.soft(Math.abs(v),c,k)}
  applySpin(b,dt){b.lift=0;if(Math.abs(b.spin)<.01)return;let v=speedOf(b);if(v<1)return;let lift=this.softSigned(b.spin,CFG.ball.spinSoftCap,CFG.ball.spinCompression)*CFG.ball.magnus*v;b.vx+=(-b.vy/v)*lift*dt;b.vy+=(b.vx/v)*lift*dt;b.spin=this.softSigned(b.spin*Math.pow(CFG.ball.spinDecay,dt),CFG.ball.spinSoftCap*1.18,CFG.ball.spinCompression);b.lift=Math.abs(lift);if(b.lift/v>1.35){b.spin*=.7;if(Math.abs(b.vx)<v*.38)b.vx=sign(b.vx)*v*.38}this.preventBacktrack(b)}
  stabilize(b,force=false){if(!Number.isFinite(b.vx)||!Number.isFinite(b.vy)){b.vx=sign(Math.random()-.5)*CFG.ball.minSpeed;b.vy=rand(-120,120);b.spin=0;return}let v=speedOf(b);if(v<CFG.ball.minSpeed){let q=CFG.ball.minSpeed/Math.max(v,1);b.vx*=q;b.vy*=q}if(force)this.escapeBall(b);v=speedOf(b);if(v>CFG.ball.speedSoftCap){let lim=this.soft(v,CFG.ball.speedSoftCap,CFG.ball.speedCompression);b.vx*=lim/v;b.vy*=lim/v}b.spin=this.softSigned(b.spin,CFG.ball.spinSoftCap,CFG.ball.spinCompression);this.preventBacktrack(b)}
  preventBacktrack(b){if(b.lastHit!=='player'&&b.lastHit!=='enemy')return;let v=speedOf(b),dir=b.lastHit==='player'?1:-1,min=v*.42;if(b.vx*dir<min){b.vx=dir*min;b.vy=clamp(b.vy,-v*.86,v*.86);b.spin*=.55}}
  escapeBall(b){let v=Math.max(speedOf(b),CFG.ball.minSpeed),dir=b.lastHit==='player'?1:b.lastHit==='enemy'?-1:sign(b.vx),a=rand(.22,.46);b.vx=dir*Math.cos(a)*v;b.vy=sign(b.vy||rand(-1,1))*Math.sin(a)*v;b.spin*=.72;b.wallBounces=0;b.stall=0;b.anchorX=b.x;b.anchorY=b.y;this.notify('BALL ESCAPED STALL',Colors.cyan,.8)}
  updateStall(b,dt){let center=b.x>this.W*.31&&b.x<this.W*.69,m=Math.hypot(b.x-b.anchorX,b.y-b.anchorY);if(!center||m>90){b.stall=0;b.warned=false;b.anchorX=b.x;b.anchorY=b.y;return}b.stall+=dt;if(!b.warned&&b.stall>1.35){b.warned=true;this.notify('TUNNEL SOON',Colors.purple,.7)}if(b.stall>2.35)this.escapeBall(b)}
  wallBounce(b,top){let now=performance.now();if(!b.wallAt||now-b.wallAt>1200)b.wallBounces=0;b.wallAt=now;b.wallBounces++;if(top){b.y=CFG.pad+b.r;b.vy=Math.abs(b.vy)}else{b.y=this.H-CFG.pad-b.r;b.vy=-Math.abs(b.vy)}this.wallSpin(b,top);this.stabilize(b,b.wallBounces>=3);this.burst(b.x,b.y,Colors.cyan,b.wallBounces>=2?16:7)}
  wallSpin(b,top){let n=top?1:-1,slip=b.vx-b.spin*b.r*n;b.vx+=-slip*.035;b.spin+=slip*.0014*n;b.spin=this.softSigned(b.spin*.72,CFG.ball.spinSoftCap*.82,CFG.ball.spinCompression);if(Math.abs(b.spin)>.06){b.vx+=sign(b.vx||1)*Math.abs(b.spin)*8;b.vy+=sign(b.vy||n)*Math.abs(b.spin)*12}this.preventBacktrack(b)}
  paddleRect(p){return{x:p.x-p.w/2,y:p.y-p.h/2,w:p.w,h:p.h}} local(p,x,y){let dx=x-p.x,dy=y-p.y,ca=Math.cos(-p.angle),sa=Math.sin(-p.angle);return{x:dx*ca-dy*sa,y:dx*sa+dy*ca}}
  rotatedHit(p,b){let q=this.local(p,b.x,b.y),hw=p.w/2,hh=p.h/2,cx=clamp(q.x,-hw,hw),cy=clamp(q.y,-hh,hh),dx=q.x-cx,dy=q.y-cy;return{hit:dx*dx+dy*dy<=b.r*b.r,rel:clamp(q.y/hh,-1,1)}}
  paddleHit(b,p,side){let hit=side?this.rotatedHit(p,b):{hit:circleRect(b,this.paddleRect(p)),rel:clamp((b.y-p.y)/(p.h/2),-1,1)};if(!hit.hit)return;if(side&&b.vx>0)return;if(!side&&b.vx<0)return;let rel=hit.rel,inc=Math.max(CFG.ball.minSpeed,speedOf(b));if(side){let n={x:Math.cos(p.angle),y:Math.sin(p.angle)},tan={x:-Math.sin(p.angle),y:Math.cos(p.angle)},bn=-(b.vx*n.x+b.vy*n.y),pn=p.vx*n.x+p.vy*n.y,pt=p.vx*tan.x+p.vy*tan.y,out=Math.max(CFG.ball.minSpeed,inc*.97+Math.max(0,bn+pn)*CFG.ball.contactGain+Math.max(0,pn)*CFG.ball.paddlePush),launch=p.angle+rel*.52,spin=clamp(pt/650+pn/1200+p.angle*.18+rel*.35+this.spinIntent,-2.2,2.2);b.spin=clamp(b.spin*.28+spin*this.mods.spinPower,-CFG.ball.maxSpin,CFG.ball.maxSpin);b.vx=Math.cos(launch)*out+tan.x*pt*.08;b.vy=Math.sin(launch)*out+tan.y*pt*.08+rand(-5,5);b.contact=Math.max(0,bn+pn);b.paddleV=Math.hypot(p.vx,p.vy);b.x=p.x+Math.cos(p.angle)*(p.w/2+b.r+1);b.y=p.y+Math.sin(p.angle)*(p.w/2+b.r+1)+rel*p.h*.36;if(Math.abs(this.spinIntent)>.35)this.notify('SPIN LOAD RELEASE',this.spinIntent>0?Colors.gold:Colors.purple,.8);this.spinIntent*=.34}else{let a=rel*.82,out=Math.max(CFG.ball.minSpeed,inc*(p.kind&&p.kind.startsWith('boss')?1.11:1.075)),tg=clamp(p.vy/620+rel*.46,-1.7,1.7);b.spin=clamp(b.spin*.28+tg*.7,-CFG.ball.maxSpin,CFG.ball.maxSpin);b.vx=-Math.cos(a)*out;b.vy=Math.sin(a)*out+p.vy*.15+rand(-7,7);b.contact=inc;b.paddleV=Math.abs(p.vy);b.x=p.x-p.w/2-b.r-1}b.lastHit=side?'player':'enemy';b.wallBounces=0;b.stall=0;b.anchorX=b.x;b.anchorY=b.y;this.stabilize(b);this.burst(b.x,b.y,side?Colors.cyan:p.color,Math.abs(b.spin)>.65?22:12);if(Math.abs(b.spin)>.65)this.notify(b.spin>0?'TOPSPIN':'BACKSPIN',b.spin>0?Colors.gold:Colors.purple,.55)}
  blockHit(b){for(let i=this.blocks.length-1;i>=0;i--){let o=this.blocks[i];if(!circleRect(b,o))continue;let cx=o.x+o.w/2,cy=o.y+o.h/2,dx=(b.x-cx)/(o.w/2),dy=(b.y-cy)/(o.h/2);if(Math.abs(dx)>Math.abs(dy)){let q=dx>=0?1:-1;b.vx=Math.abs(b.vx)*q;b.x=cx+q*(o.w/2+b.r+.8);b.spin*=.96}else{let q=dy>=0?1:-1;b.vy=Math.abs(b.vy)*q;b.y=cy+q*(o.h/2+b.r+.8);b.spin*=.94}this.stabilize(b);this.handleBlock(o,b,i,cx,cy);return}}
  handleBlock(o,b,i,x,y){if(o.cool>0&&(o.type==='portal'||o.type==='wormhole'))return;let shield=o.type==='shielded'&&o.hp===o.maxHp,spinBreak=Math.abs(b.spin)>=CFG.ball.spinSoftCap*.8,damage=b.damage+(spinBreak&&!shield?1:0)+(o.type==='bosscore'?this.mods.bossBane:0);o.hp-=shield?0:damage;if(shield){o.type='stone';o.hp=Math.max(2,o.hp-1);this.notify('SHIELD BREAK',Colors.cyan,.8)}this.addScore((o.type==='bosscore'?60:22)*damage,x,y);this.burst(x,y,this.blockColor(o.type),spinBreak?22:12);if(o.type==='portal'||o.type==='wormhole')this.teleportBall(b,o);if(o.type==='pinhole'&&Math.random()<this.mods.pinholeChance)this.pinholeSplit(b,x,y);if(o.type==='splitter')this.pinholeSplit(b,x,y,true);if(o.type==='entangler')this.entangleBall(b,x,y);if(o.type==='mirror'){b.vx*=-1;b.lastHit=b.lastHit==='player'?'enemy':'player';this.notify('MIRROR REFLECT',Colors.text,.65)}if(o.type==='observer')this.collapseWave(b,x,y);if(o.type==='bonus')this.bonusEffect(b,x,y);if(o.type==='spike'&&b.lastHit!=='player'&&!this.mods.phaseSafe)this.hurtPlayer(1);if(o.hp<=0){this.blocks.splice(i,1);if(o.type==='portal'||o.type==='wormhole')this.linkPortals();this.scheduleBlock();this.breakEffect(o,b,x,y);this.addScore(this.blockScore(o),x,y,o.type.toUpperCase())}}
  teleportBall(b,o){let holes=this.blocks.filter(x=>(x.type==='portal'||x.type==='wormhole')&&x!==o),target=o.link&&o.link!==o?o.link:pick(holes);if(!target)return;o.cool=target.cool=.7;b.x=target.x+target.w/2+rand(-8,8);b.y=target.y+target.h/2+rand(-8,8);let boost=this.mods.portalMastery?1.16:1.04;b.vx*=boost;b.vy=b.vy*boost+rand(-70,70)*(this.mods.phaseSafe?.35:1);this.notify(o.type==='wormhole'?'WORMHOLE':'PORTAL',Colors.purple,.8);this.burst(b.x,b.y,Colors.purple,24)}
  pinholeSplit(src,x,y,forced=false){if(!forced&&this.balls.length>=this.maxBalls())return;let v=Math.max(CFG.ball.minSpeed,speedOf(src)*.92),dir=sign(src.vx||1),group=Math.random().toString(36).slice(2),a=.34+Math.random()*.18;this.makeBall(x,y,dir*Math.cos(a)*v,Math.sin(a)*v,src.spin*.72,src.lastHit,group);this.makeBall(x,y,dir*Math.cos(-a)*v,Math.sin(-a)*v,-src.spin*.72,src.lastHit,group);this.notify('DOUBLE-SLIT SPLIT',Colors.cyan,1)}
  entangleBall(src,x,y){if(this.balls.length<2)this.pinholeSplit(src,x,y,true);let g=src.entangled||Math.random().toString(36).slice(2);src.entangled=g;for(let b of this.balls)if(Math.hypot(b.x-src.x,b.y-src.y)<180)b.entangled=g;this.notify('ENTANGLED',Colors.green,.9)}
  collapseWave(b,x,y){let group=b.entangled,n=1;if(group)for(let o of this.balls)if(o!==b&&o.entangled===group){o.vx=b.vx*rand(.84,1.16);o.vy=-b.vy*rand(.84,1.16);o.spin=-b.spin;n++}this.addScore(this.mods.collapseBonus+n*65,x,y,'WAVE COLLAPSE');this.notify('WAVE COLLAPSE',Colors.gold,1);this.burst(x,y,Colors.gold,28)}
  updateQuantum(dt){let groups=new Map();for(let b of this.balls)if(b.entangled){if(!groups.has(b.entangled))groups.set(b.entangled,[]);groups.get(b.entangled).push(b)}for(let balls of groups.values()){if(balls.length<2)continue;let avgSpin=balls.reduce((s,b)=>s+b.spin,0)/balls.length,avgSpeed=balls.reduce((s,b)=>s+speedOf(b),0)/balls.length;for(let b of balls){b.spin+=(avgSpin-b.spin)*dt*1.4*this.mods.entanglePower;let v=speedOf(b);if(v>1){let target=v+(avgSpeed-v)*dt*.9*this.mods.entanglePower;b.vx*=target/v;b.vy*=target/v}if(Math.random()<dt*.025/this.mods.entanglePower)b.entangled=null}}}
  bonusEffect(b,x,y){let e=pick(['heal','score','shield','stun','speed','curve','pinhole']);if(e==='heal'){this.player.hp=Math.min(this.mods.maxHp,this.player.hp+1);this.notify('HEAL',Colors.green,.8)}if(e==='score')this.addScore(260+this.level*12,x,y,'BONUS');if(e==='shield'){this.mods.shield++;this.notify('AEGIS +1',Colors.cyan,.8)}if(e==='stun'){this.enemy.stun=Math.max(this.enemy.stun,.5+this.mods.stunBonus);this.notify('ENEMY SNARED',Colors.purple,.8)}if(e==='speed'){b.vx*=1.16;b.vy*=1.16;this.notify('BOOST',Colors.gold,.8)}if(e==='curve'){b.spin=clamp(b.spin+rand(-1.3,1.3),-CFG.ball.maxSpin,CFG.ball.maxSpin);this.notify('CURVE SHIFT',Colors.orange,.8)}if(e==='pinhole')this.pinholeSplit(b,x,y,true)}
  breakEffect(o,b,x,y){if(o.type==='bomb'){for(let i=this.blocks.length-1;i>=0;i--){let z=this.blocks[i];if(Math.hypot(z.x+z.w/2-x,z.y+z.h/2-y)<92){this.blocks.splice(i,1);this.addScore(44,z.x+z.w/2,z.y+z.h/2,'CHAIN');this.burst(z.x+z.w/2,z.y+z.h/2,this.blockColor(z.type),14)}}b.vx*=1.12;b.vy*=1.12;this.notify('BOMB CHAIN',Colors.red,.9)}if(o.type==='bosscore'){this.enemy.stun=Math.max(this.enemy.stun,1+this.mods.stunBonus);this.mods.shield++;this.notify('BOSS CORE BROKEN',Colors.red,1.2)}}
  blockScore(o){return{spike:80,portal:95,wormhole:115,pinhole:105,entangler:125,mirror:120,splitter:110,moving:125,gravity:135,regen:140,shielded:155,bomb:180,observer:190,bosscore:520,bonus:180}[o.type]||50}
  goalDamage(b){let d=b.damage+(this.enemy.kind&&this.enemy.kind.startsWith('boss')?this.mods.bossBane:0);if(Math.abs(b.spin)>.9){d++;this.notify('SPIN GOAL +1',Colors.gold,.8)}if(Math.random()<this.mods.crit){d*=2;this.notify('CRITICAL GOAL',Colors.gold,1)}return d}
  hurtPlayer(n){if(this.player.inv>0)return;if(this.mods.shield>0){this.mods.shield--;this.notify('SHIELD ABSORBED',Colors.cyan,.9);this.burst(this.player.x,this.player.y,Colors.cyan,28);return}this.player.hp-=n;this.player.inv=1;this.combo=0;this.flash=.22;this.notify('DAMAGE',Colors.pink,1);this.burst(this.player.x,this.player.y,Colors.pink,34);if(this.player.hp<=0){this.mode='gameover';this.saveBest();this.syncButton()}}
  hitEnemy(n,x,y){this.enemy.hp-=n;this.enemy.stun=Math.max(this.enemy.stun,.12);this.addScore(75*n,x,y,'-'+n+' HP');this.notify('HIT '+n,Colors.gold,.7);this.burst(x,y,this.enemy.color,20+n*5);if(this.enemy.hp<=0&&this.mode==='playing'){this.balls=[];this.addScore(260+this.level*55,this.W/2,this.H/2,this.isBossLevel()?'BOSS CLEAR':'LEVEL CLEAR');this.mode='cleared';setTimeout(()=>{if(this.mode==='cleared')this.createDraft()},450)}}
  addScore(points,x,y,label){let gain=Math.round(points*this.mods.scoreScale*(1+Math.min(1.8,this.combo*.055)));this.score+=gain;this.combo++;this.comboTimer=2.1;this.floatText(x,y,label||'+'+gain,Colors.gold)}
  floatText(x,y,text,color){this.floaters.push({x,y,text,color,life:.82,vy:-38})}
  burst(x,y,color,n){for(let i=0;i<n;i++){let a=rand(0,Math.PI*2),v=rand(35,240);this.particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,r:rand(1.2,3.4),color,life:rand(.25,.85)})}}
  updateEffects(dt){for(let p of this.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.06,dt);p.vy*=Math.pow(.06,dt);p.life-=dt}this.particles=this.particles.filter(p=>p.life>0);for(let f of this.floaters){f.y+=f.vy*dt;f.life-=dt}this.floaters=this.floaters.filter(f=>f.life>0);for(let n of this.notes)n.life-=dt;this.notes=this.notes.filter(n=>n.life>0)}
  saveBest(){if(this.score>this.best){this.best=this.score;localStorage.setItem('thats-a-paddlin-best',this.best)}}
  createDraft(){let repeat=new Set(['heart','shield','luck','meteor','comet','echo']),pool=Relics.filter(r=>!this.relics.includes(r.id)||repeat.has(r.id));this.draft=[];while(this.draft.length<3&&pool.length){let r=pick(pool);if(!this.draft.includes(r))this.draft.push(r)}this.mode='upgrade';this.notify('LEVEL UP - CHOOSE UPGRADE',Colors.gold,2);this.syncButton()}
  chooseRelic(i){if(this.mode!=='upgrade'||!this.draft[i])return;let r=this.draft[i];r.apply(this.mods,this);this.relics.push(r.id);this.notify('UPGRADE: '+r.name.toUpperCase(),Colors.gold,1.4);this.level++;if(this.level>CFG.maxLevel){this.mode='victory';this.saveBest();this.syncButton();return}this.enemy=this.makeEnemy();this.balls=[];this.fillBlocks();this.mode='playing';this.prepareFreeServe();this.syncButton()}
  values(){let b=this.balls[0],p=this.player;return[['Ball',speedOf(b).toFixed(0),Colors.cyan],['Trail',b?b.trail.length+'/'+this.trailLimit(b):'0',Colors.cyan],['Level',this.level+'/'+CFG.maxLevel,Colors.gold],['Enemy',this.enemy?this.enemy.kind:'none',Colors.pink],['Spin',b?b.spin.toFixed(2):'0',b&&b.spin>=0?Colors.gold:Colors.purple],['Load',Math.round(Math.abs(this.spinIntent)*100)+'%',this.spinIntent>=0?Colors.gold:Colors.purple],['Angle',p?(p.angle*180/Math.PI).toFixed(0)+' deg':'0',Colors.cyan],['Stamina',p?Math.round(p.stamina*100)+'%':'0',p&&p.wait>0?Colors.pink:Colors.green],['Blocks',this.blocks.length+'+'+this.previews.length,Colors.text],['Balls',String(this.balls.length),Colors.text],['Ent',String(this.balls.filter(x=>x.entangled).length),Colors.green],['Shield',String(this.mods?this.mods.shield:0),Colors.text]]}
  syncButton(){if(this.mode==='title'){this.button.hidden=false;this.button.textContent='Start game'}else if(this.mode==='gameover'||this.mode==='victory'){this.button.hidden=false;this.button.textContent='Restart'}else this.button.hidden=true}
}
