import { Colors, CFG } from './config.js';
import { clamp, roundPath, heartPath } from './utils.js';

export class Renderer {
  constructor(game, ctx) { this.game = game; this.ctx = ctx; }
  draw() {
    const g = this.game, ctx = this.ctx, W = g.W, H = g.H;
    ctx.setTransform(g.dpr, 0, 0, g.dpr, 0, 0);
    ctx.clearRect(0, 0, W, H);
    ctx.save();
    if (g.shake) ctx.translate((Math.random() * 2 - 1) * g.shake, (Math.random() * 2 - 1) * g.shake);
    this.background(); this.arena(); this.zones(); this.previews(); this.blocks();
    if (g.player && g.enemy) { this.paddle(g.player, g.player.inv > 0 ? .55 : 1, true); this.paddle(g.enemy, g.enemy.stun > 0 ? .55 : 1, false); this.stamina(g.player, true); this.stamina(g.enemy, false); }
    this.balls(); this.effects(); this.hud();
    ctx.restore();
    if (g.flash > 0) { ctx.fillStyle = `rgba(255,95,126,${g.flash})`; ctx.fillRect(0,0,W,H); }
    if (g.mode === 'title') this.title();
    if (g.mode === 'upgrade') this.upgrades();
    if (g.mode === 'gameover') this.end(false);
    if (g.mode === 'victory') this.end(true);
    if (g.paused) this.pause();
  }
  background(){const {ctx}=this,W=this.game.W,H=this.game.H;const grad=ctx.createLinearGradient(0,0,W,H);grad.addColorStop(0,'#101735');grad.addColorStop(.55,'#070914');grad.addColorStop(1,'#16091c');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);ctx.save();ctx.globalAlpha=.14;ctx.strokeStyle=Colors.cyan;for(let x=-H;x<W+H;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x-H*.22,H);ctx.stroke()}ctx.restore()}
  arena(){const {ctx}=this,g=this.game;ctx.save();ctx.strokeStyle='rgba(255,255,255,.16)';ctx.lineWidth=2;roundPath(ctx,CFG.pad,CFG.pad,g.W-CFG.pad*2,g.H-CFG.pad*2,22);ctx.stroke();ctx.setLineDash([8,14]);ctx.beginPath();ctx.moveTo(g.W/2,30);ctx.lineTo(g.W/2,g.H-30);ctx.stroke();ctx.restore()}
  zones(){for(const [z,col] of [[this.game.playerZone(),Colors.cyan],[this.game.enemyZone(),Colors.pink]]){this.ctx.save();this.ctx.globalAlpha=.08;this.ctx.fillStyle=col;roundPath(this.ctx,z.x1,CFG.pad+12,z.x2-z.x1,this.game.H-CFG.pad*2-24,18);this.ctx.fill();this.ctx.globalAlpha=.22;this.ctx.strokeStyle=col;this.ctx.setLineDash([8,10]);this.ctx.stroke();this.ctx.restore()}}
  previews(){const ctx=this.ctx;for(const p of this.game.previews){const r=clamp(1-p.time/p.total,0,1),col=this.game.blockColor(p.type);ctx.save();ctx.globalAlpha=.22+r*.35;ctx.strokeStyle=col;ctx.fillStyle=col;ctx.setLineDash([7,7]);roundPath(ctx,p.x,p.y,p.w,p.h,7);ctx.stroke();ctx.globalAlpha=.1+r*.18;ctx.fill();ctx.setLineDash([]);ctx.fillStyle=Colors.text;ctx.font='800 10px sans-serif';ctx.textAlign='center';ctx.fillText(p.type,p.x+p.w/2,p.y-7);ctx.restore()}}
  blocks(){const ctx=this.ctx;for(const b of this.game.blocks){const col=this.game.blockColor(b.type);ctx.save();ctx.shadowColor=col;ctx.shadowBlur=b.type==='portal'||b.type==='wormhole'?18:7;ctx.fillStyle=col;ctx.globalAlpha=b.type==='stone'?.75:.9;roundPath(ctx,b.x,b.y,b.w,b.h,7);ctx.fill();ctx.globalAlpha=1;ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,255,255,.24)';ctx.stroke();if(b.maxHp>1){ctx.fillStyle='rgba(0,0,0,.38)';ctx.fillRect(b.x+4,b.y+b.h-6,b.w-8,3);ctx.fillStyle=Colors.text;ctx.fillRect(b.x+4,b.y+b.h-6,(b.w-8)*b.hp/b.maxHp,3)}ctx.fillStyle='rgba(0,0,0,.50)';ctx.textAlign='center';ctx.font='900 13px sans-serif';ctx.fillText({bonus:'+',pinhole:'||',entangler:'8',mirror:'<>',gravity:'@',observer:'O',bomb:'o',splitter:'<',regen:'R',shielded:'D',wormhole:'W',portal:'P',bosscore:'B',spike:'^'}[b.type]||'',b.x+b.w/2,b.y+b.h/2+4);ctx.restore()}}
  stamina(p,player){const ctx=this.ctx,w=46,h=5,x=p.x-w/2,y=p.y+p.h/2+12;ctx.save();ctx.globalAlpha=.88;ctx.fillStyle='rgba(0,0,0,.44)';roundPath(ctx,x,y,w,h,3);ctx.fill();ctx.fillStyle=p.wait>0?Colors.pink:player?Colors.cyan:p.color;roundPath(ctx,x,y,w*clamp(p.stamina,0,1),h,3);ctx.fill();ctx.restore()}
  paddle(p,a=1,angled=true){const ctx=this.ctx,g=this.game;ctx.save();ctx.translate(p.x,p.y);if(angled)ctx.rotate(p.angle);ctx.globalAlpha=a;ctx.shadowColor=p.color;ctx.shadowBlur=18;const grad=ctx.createLinearGradient(-p.w/2,-p.h/2,p.w/2,p.h/2);grad.addColorStop(0,p.color);grad.addColorStop(1,'#fff');ctx.fillStyle=grad;roundPath(ctx,-p.w/2,-p.h/2,p.w,p.h,8);ctx.fill();if(angled&&p.angleLocked){ctx.shadowBlur=0;ctx.strokeStyle=Colors.gold;ctx.lineWidth=2;roundPath(ctx,-p.w/2-3,-p.h/2-3,p.w+6,p.h+6,10);ctx.stroke()}if(angled&&p===g.player&&Math.abs(g.spinIntent)>.04){const q=Math.sign(g.spinIntent),l=Math.abs(g.spinIntent);ctx.shadowBlur=0;ctx.globalAlpha=.32+l*.5;ctx.strokeStyle=q>0?Colors.gold:Colors.purple;ctx.lineWidth=2+l*2;ctx.beginPath();ctx.moveTo(-p.w/2-8,-p.h/2+4);ctx.quadraticCurveTo(-p.w/2-10-l*18*q,0,-p.w/2-8,p.h/2-4);ctx.stroke()}ctx.restore()}
  balls(){const ctx=this.ctx,g=this.game;for(const b of g.balls){for(let i=0;i<b.trail.length;i++){const q=b.trail[i],seq=(i+1)/Math.max(1,b.trail.length),life=clamp(q.life/(q.max||.22),0,1),sr=clamp((q.speed||0)/CFG.ball.speedSoftCap,0,2.5);ctx.save();ctx.globalAlpha=life*seq*(.13+Math.min(.45,sr*.24));ctx.fillStyle=q.full?(Math.random()<.5?Colors.gold:Colors.cyan):Math.abs(b.spin)>.7?Colors.gold:Colors.cyan;ctx.beginPath();ctx.arc(q.x,q.y,(q.r||b.r)*seq*life,0,Math.PI*2);ctx.fill();if(q.full){ctx.strokeStyle=Colors.text;ctx.globalAlpha*=.55;ctx.beginPath();ctx.arc(q.x,q.y,(q.r||b.r)*seq*life*1.35,0,Math.PI*2);ctx.stroke()}ctx.restore()}ctx.save();ctx.shadowColor=g.trailRatio(b)>=1?Colors.gold:Math.abs(b.spin)>.7?Colors.gold:Colors.cyan;ctx.shadowBlur=g.trailRatio(b)>=1?32:22;const gr=ctx.createRadialGradient(b.x-3,b.y-3,1,b.x,b.y,b.r+5);gr.addColorStop(0,'#fff');gr.addColorStop(.5,Colors.cyan);gr.addColorStop(1,'rgba(255,255,255,.16)');ctx.fillStyle=gr;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();if(b.entangled){ctx.strokeStyle=Colors.green;ctx.globalAlpha=.7;ctx.beginPath();ctx.arc(b.x,b.y,b.r+9,0,Math.PI*2);ctx.stroke()}ctx.restore()}}
  effects(){const ctx=this.ctx;for(const p of this.game.particles){ctx.save();ctx.globalAlpha=clamp(p.life,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();ctx.restore()}for(const f of this.game.floaters){ctx.save();ctx.globalAlpha=clamp(f.life*1.25,0,1);ctx.fillStyle=f.color;ctx.font='800 16px sans-serif';ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y);ctx.restore()}}
  hud(){const g=this.game,ctx=this.ctx;if(!g.player||!g.enemy)return;const w=Math.min(Math.max(610,g.W*.58),g.W-28),h=g.W<760?128:98,x=g.W/2-w/2,y=10;ctx.save();ctx.fillStyle='rgba(0,0,0,.36)';roundPath(ctx,x,y,w,h,14);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.14)';ctx.stroke();this.stats(x,y,w);this.physics(x,y+41,w);this.notes();if(g.freeServe){ctx.textAlign='center';ctx.fillStyle=Colors.cyan;ctx.font='900 18px sans-serif';ctx.fillText('Click or press Space to serve',g.W/2,g.H/2-74)}ctx.restore()}
  stats(x,y,w){const g=this.game,ctx=this.ctx,c=x+w/2;ctx.textAlign='center';ctx.fillStyle=Colors.text;ctx.font='900 13px sans-serif';ctx.fillText('Level '+g.level+'/'+CFG.maxLevel,c-w*.39,y+20);for(let i=0;i<g.mods.maxHp;i++){ctx.fillStyle=i<g.player.hp?Colors.pink:'rgba(255,255,255,.16)';heartPath(ctx,c-w*.28+i*16,y+18,6);ctx.fill()}this.enemyBar(c-w*.07,y+12,Math.min(164,w*.24));ctx.fillStyle=Colors.gold;ctx.font='900 14px sans-serif';ctx.fillText(String(g.score).padStart(6,'0'),c+w*.32,y+20);ctx.fillStyle=Colors.muted;ctx.font='700 10px sans-serif';ctx.fillText('BEST '+g.best,c+w*.32,y+34)}
  enemyBar(x,y,w){const ctx=this.ctx,e=this.game.enemy;ctx.fillStyle='rgba(255,255,255,.12)';roundPath(ctx,x,y,w,8,6);ctx.fill();ctx.fillStyle=e.color;roundPath(ctx,x,y,w*clamp(e.hp/e.maxHp,0,1),8,6);ctx.fill();ctx.fillStyle=Colors.muted;ctx.font='700 10px sans-serif';ctx.textAlign='center';ctx.fillText(e.kind+' '+Math.max(0,e.hp)+'/'+e.maxHp,x+w/2,y+22)}
  physics(x,y,w){const ctx=this.ctx,cols=this.game.W<760?3:5,cw=w/cols,rh=this.game.W<760?14:13;ctx.font='800 9px sans-serif';ctx.textAlign='left';this.game.values().forEach(([l,v,col],i)=>{const tx=x+12+(i%cols)*cw,ty=y+Math.floor(i/cols)*rh;ctx.fillStyle=Colors.muted;ctx.fillText(l,tx,ty);ctx.fillStyle=col||Colors.text;ctx.fillText(v,tx+56,ty)})}
  notes(){const ctx=this.ctx,g=this.game;ctx.textAlign='center';g.notes.forEach((n,i)=>{const a=clamp(n.life/n.maxLife,0,1);ctx.globalAlpha=a;ctx.fillStyle=n.color;ctx.font=i===g.notes.length-1?'900 26px sans-serif':'900 15px sans-serif';ctx.fillText(n.text,g.W/2,g.H/2-126-i*24);ctx.globalAlpha=1})}
  overlay(a){this.ctx.fillStyle=`rgba(5,7,18,${a})`;this.ctx.fillRect(0,0,this.game.W,this.game.H)}
  title(){const ctx=this.ctx,g=this.game;this.overlay(.75);ctx.save();ctx.textAlign='center';ctx.fillStyle=Colors.text;ctx.font=`900 ${clamp(g.W*.07,42,76)}px sans-serif`;ctx.fillText("that's a paddlin",g.W/2,g.H*.27);ctx.fillStyle=Colors.cyan;ctx.font='900 22px sans-serif';ctx.fillText('50-level quantum roguelike pong',g.W/2,g.H*.27+42);ctx.fillStyle=Colors.muted;ctx.font='600 18px sans-serif';this.wrap('Boss enemies every 5 levels. Quantum blocks split, entangle, collapse, and teleport the ball. Fast balls leave growing photon trails with full-speed flare effects.',g.W/2,g.H*.43,Math.min(860,g.W-50),28);this.button(g.W/2-132,g.H*.62,264,58,'Start game',Colors.cyan);ctx.restore()}
  upgrades(){const ctx=this.ctx,g=this.game;this.overlay(.78);ctx.save();ctx.textAlign='center';ctx.fillStyle=Colors.text;ctx.font='900 44px sans-serif';ctx.fillText('Choose an Upgrade',g.W/2,92);ctx.fillStyle=Colors.muted;ctx.font='700 16px sans-serif';ctx.fillText('Click a card or press 1, 2, or 3.',g.W/2,122);const comp=g.W<820,cw=comp?Math.min(286,g.W-40):258,ch=comp?134:224,gap=18,sx=comp?g.W/2-cw/2:g.W/2-(cw*3+gap*2)/2,sy=comp?150:180;g.draft.forEach((r,i)=>this.card(r,i,comp?sx:sx+i*(cw+gap),comp?sy+i*(ch+14):sy,cw,ch,comp));ctx.restore()}
  card(r,i,x,y,w,h,comp){const ctx=this.ctx;ctx.save();ctx.fillStyle='rgba(14,18,37,.94)';ctx.strokeStyle='rgba(255,255,255,.18)';ctx.lineWidth=2;roundPath(ctx,x,y,w,h,18);ctx.fill();ctx.stroke();ctx.fillStyle=Colors.gold;ctx.font=comp?'900 34px sans-serif':'900 48px sans-serif';ctx.fillText(r.icon,x+w/2,y+(comp?42:64));ctx.fillStyle=Colors.text;ctx.font=comp?'900 18px sans-serif':'900 22px sans-serif';ctx.fillText((i+1)+'. '+r.name,x+w/2,y+(comp?72:106));ctx.fillStyle=Colors.muted;ctx.font=comp?'700 13px sans-serif':'700 15px sans-serif';this.wrap(r.desc,x+w/2,y+(comp?98:144),w-42,comp?18:22);ctx.restore()}
  end(win){const ctx=this.ctx,g=this.game;this.overlay(.76);ctx.save();ctx.textAlign='center';ctx.fillStyle=win?Colors.gold:Colors.pink;ctx.font=`900 ${clamp(g.W*.06,42,64)}px sans-serif`;ctx.fillText(win?'Quantum Dungeon Cleared':'Run Ended',g.W/2,g.H*.32);ctx.fillStyle=Colors.text;ctx.font='900 26px sans-serif';ctx.fillText('Score '+g.score+' - Best '+g.best,g.W/2,g.H*.32+50);this.button(g.W/2-120,g.H*.54,240,54,'Restart',win?Colors.gold:Colors.pink);ctx.restore()}
  pause(){const ctx=this.ctx,g=this.game;this.overlay(.68);ctx.save();ctx.textAlign='center';ctx.fillStyle=Colors.text;ctx.font='900 54px sans-serif';ctx.fillText('Paused',g.W/2,g.H*.18);const bw=Math.min(780,g.W-38),bh=416,x=g.W/2-bw/2,y=g.H*.25;ctx.fillStyle='rgba(14,18,37,.92)';roundPath(ctx,x,y,bw,bh,18);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.18)';ctx.stroke();['Controls','Mouse/touch: paddle center snaps to pointer in the left third','Enemy starts faster and owns the right third','A/D or Arrow keys: rotate and load spin','Quantum blocks: pinhole split, entangle, observer collapse, portals/wormholes','Boss enemy every 5 levels; 50 total levels','Fast balls leave larger trails; full speed creates photon flare','1/2/3: choose upgrade - P: resume - R: restart'].forEach((line,i)=>{ctx.fillStyle=i?Colors.muted:Colors.cyan;ctx.font=i?'700 15px sans-serif':'900 20px sans-serif';ctx.fillText(line,g.W/2,y+34+i*27)});ctx.restore()}
  button(x,y,w,h,text,color){const ctx=this.ctx;ctx.save();ctx.shadowColor=color;ctx.shadowBlur=18;ctx.fillStyle=color;roundPath(ctx,x,y,w,h,16);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='rgba(0,0,0,.72)';ctx.font='900 18px sans-serif';ctx.textAlign='center';ctx.fillText(text,x+w/2,y+h/2+6);ctx.restore()}
  wrap(text,x,y,max,lineH){const ctx=this.ctx,words=text.split(' ');let line='';for(const word of words){const test=line+word+' ';if(ctx.measureText(test).width>max&&line){ctx.fillText(line.trim(),x,y);line=word+' ';y+=lineH}else line=test}ctx.fillText(line.trim(),x,y)}
}
